version: "3"
services:
  mongo:
    volumes:
      - /data/filebase/develop:/data/db

  api:
    ports:
      - 3333:3333
      - 3012:3012

  frontend:
    environment:
      - DOMAIN=http://localhost:3333
      - DOMAIN_AUTH=http://localhost:3012
    ports:
      - 1234:80
